-- =============================================================================
-- Pick slips & dispatch advices — private Storage bucket
-- Migration: 00031_order_documents_bucket.sql
-- =============================================================================
-- Holds the PDFs generated by the warehouse fulfillment flow:
--   order-documents/{order_id}/pick-slip-{ts}.pdf
--   order-documents/{order_id}/dispatch-advice-{ts}.pdf
--
-- Private bucket (no anonymous access); the UI fetches each doc through a
-- short-lived signed URL issued server-side by the generate-pick-slip /
-- generate-dispatch-advice Edge Functions. The order_documents table (mig
-- 00027) records the storage_path so the UI can list/regenerate signed URLs.
-- Mirrors the 00019 po-archive pattern. Reads allowed to ops roles only
-- (Admin/Manager/Warehouse); all writes go through the service_role.
-- =============================================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'order-documents',
    'order-documents',
    false,                              -- private
    10 * 1024 * 1024,                   -- 10 MB / object (PDFs are small)
    ARRAY['application/pdf']
)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "order_documents_select_ops"
    ON storage.objects FOR SELECT
    TO authenticated
    USING (
        bucket_id = 'order-documents'
        AND (SELECT public.user_role()) IN ('Admin','Manager','Warehouse')
    );

-- =============================================================================
-- END OF MIGRATION
-- =============================================================================
