-- =============================================================================
-- Friendly location names — name provenance
-- Migration: 00094_location_name_provenance.sql
-- =============================================================================
-- `locations.name` has existed and been NOT NULL since 00027, and the layout
-- designer has always written it — with `Bin 9,4` and `Level 4`. Nothing ever
-- rendered it, so nobody noticed that the string an operator actually reads,
-- `L4 · NEXG-B-9-4-L4`, is a grid COORDINATE (x=9, y=4) and not an aisle and a
-- bay. There is no aisle or rack semantics anywhere in a location code.
--
-- This migration does not change a single name. It adds the three columns that
-- let a name be composed from the operator's own vocabulary — the named `area`
-- painted over the racks (00090) — and safely recomposed later:
--
--     name         'Chiller · Rack 7'          (already existed)
--     name_area    'Chiller'                   the POOL the number was drawn from
--     name_seq     7                           the number, assigned ONCE
--     name_is_auto true                        may an area rename restamp this?
--
-- WHY THREE COLUMNS AND NOT ONE FLAG. The obvious design is a single
-- `name_is_auto` and deriving everything else from geometry. It has a live
-- failure. Paint a "Bulk" area over cells currently named `Chiller · Rack 1..5`.
-- Nothing auto-restamps on a repaint, so those five keep their names — but a
-- geometry-derived pool for "Chiller" is now EMPTY, and the next rack drawn in
-- Chiller is minted as `Chiller · Rack 1`. Two racks, same name, both signs on
-- the floor. `name_area` fixes it by construction: a claim is held by the name a
-- row CARRIES, not by the area it currently sits in.
--
-- Equally, `name_seq` cannot be derived from position (that renumbers on delete)
-- nor parsed back out of `name` (an area name is free operator text and may
-- itself contain ' · Rack ').
--
-- WHY name_is_auto DEFAULTS TO false. `true` would be a backfill wearing a
-- disguise: it asserts every pre-existing name was generated by this feature.
-- That is false — `Bin 9,4` was generated, but a name an admin typed in the
-- warehouse tree was not, and NOTHING IN THE DATA DISTINGUISHES THEM. It would
-- also make the first area rename over MAIN silently rewrite 945 names whose QR
-- stickers are already stuck to the racking. Existing rows are therefore frozen,
-- and the operator opts them in explicitly (the "Also rename these" checkbox),
-- previewed, one deliberate click at a time.
--
-- The code is untouched and stays untouched: it is the QR payload, the scan
-- identity, a materialized_path segment and the CSV `bin_code` column.
--
-- Additive & idempotent.
-- =============================================================================

BEGIN;

-- ── 1. Provenance columns ───────────────────────────────────────────────────

ALTER TABLE public.locations
    ADD COLUMN IF NOT EXISTS name_is_auto BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS name_seq     INT,
    ADD COLUMN IF NOT EXISTS name_area    TEXT;

COMMENT ON COLUMN public.locations.name_is_auto IS
    'true = this name was composed by the layout designer and an area rename may '
    'restamp it. false (the default, and every row predating 00094) = a human '
    'typed it, or it predates the feature; the cascade skips it unless the '
    'operator explicitly opts in.';

COMMENT ON COLUMN public.locations.name_seq IS
    'The rack number within name_area. Assigned once, at draw time, and NEVER '
    'reassigned: deleting rack 3 leaves a permanent gap, because a sign already '
    'on the floor cannot be un-printed. NULL on SHELF rows — a level composes '
    'from its RACK parent''s seq plus its own level_index.';

COMMENT ON COLUMN public.locations.name_area IS
    'The area name this row''s number was drawn from — the POOL KEY, and the '
    'reason this is a stored column rather than a geometry lookup. Painting a '
    'different area over a rack must not release its claim on the old pool, or '
    'the next rack drawn there duplicates a name that is live on the floor.';

-- No index. Both consumers drive off an `id IN (...)` list assembled from
-- layout geometry, so name_seq is never a predicate.

-- ── 2. wie_rename_locations_tx — the batched writer ─────────────────────────
-- Deliberately dumb, exactly like wie_update_layout_tx (00091): the naming
-- maths is NOT restated in PL/pgSQL. The caller computes every value with the
-- one pure module both runtimes share and this applies them atomically, with a
-- scope backstop.
--
-- It exists because renaming an area over MAIN is 1134 rows (189 racks + 945
-- shelves). As per-row updates that is 1134 round trips against a 20s fetch
-- ceiling; as one statement it is one.
--
-- p_warehouse_path is the seatbelt. The caller already checks that every id it
-- resolved sits under the warehouse, but those ids came from client-supplied
-- geometry and an UPDATE must not be the first operation to take that on trust.
-- Mirrors 00091's "never let a caller's id reach another layout".

CREATE OR REPLACE FUNCTION public.wie_rename_locations_tx(
    p_warehouse_path TEXT,
    p_rows           JSONB
)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_updated  INT;
    v_expected INT;
    v_blank    INT;
BEGIN
    IF p_warehouse_path IS NULL OR btrim(p_warehouse_path) = '' THEN
        RAISE EXCEPTION 'wie_rename_locations_tx requires a warehouse path'
            USING ERRCODE = 'null_value_not_allowed';
    END IF;

    IF p_rows IS NULL OR jsonb_typeof(p_rows) <> 'array' THEN
        RAISE EXCEPTION 'wie_rename_locations_tx expects an array of rows'
            USING ERRCODE = 'invalid_parameter_value';
    END IF;

    v_expected := jsonb_array_length(p_rows);
    IF v_expected = 0 THEN
        RETURN 0;
    END IF;

    -- locations.name is NOT NULL and a blank name is unreadable, not empty.
    SELECT count(*)::INT INTO v_blank
      FROM jsonb_to_recordset(p_rows) AS r(name TEXT)
     WHERE r.name IS NULL OR btrim(r.name) = '';
    IF v_blank > 0 THEN
        RAISE EXCEPTION '% row(s) carry a blank name', v_blank
            USING ERRCODE = 'check_violation';
    END IF;

    WITH src AS (
        SELECT * FROM jsonb_to_recordset(p_rows)
            AS t(id INT, name TEXT, name_seq INT, name_area TEXT, name_is_auto BOOLEAN)
    ), upd AS (
        UPDATE public.locations l
           SET name         = src.name,
               name_seq     = src.name_seq,
               name_area    = src.name_area,
               name_is_auto = COALESCE(src.name_is_auto, true)
          FROM src
         WHERE l.id = src.id
           -- Scope backstop: the row must live under this warehouse.
           AND (l.materialized_path = p_warehouse_path
                OR l.materialized_path LIKE p_warehouse_path || '/%')
        RETURNING l.id
    )
    SELECT count(*)::INT INTO v_updated FROM upd;

    IF v_updated <> v_expected THEN
        RAISE EXCEPTION
            'Rename touched % of % locations under % — the caller''s view is stale, '
            'or an id escaped the warehouse',
            v_updated, v_expected, p_warehouse_path
            USING ERRCODE = 'serialization_failure';
    END IF;

    RETURN v_updated;
END;
$$;

-- A SECURITY DEFINER renamer reachable from the browser is a way around the
-- Edge Function role gate. Service role only.
REVOKE ALL ON FUNCTION public.wie_rename_locations_tx(TEXT, JSONB)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.wie_rename_locations_tx(TEXT, JSONB)
    TO service_role;

COMMIT;

-- Verify:
--   SELECT column_name, data_type, column_default, is_nullable
--     FROM information_schema.columns
--    WHERE table_name = 'locations' AND column_name LIKE 'name\_%';
--
--   -- No backfill happened (expect auto = 0):
--   SELECT count(*) FILTER (WHERE name_is_auto) AS auto, count(*) AS total
--     FROM public.locations;
--
--   -- Scope backstop bites (expect serialization_failure):
--   BEGIN;
--     SELECT public.wie_rename_locations_tx('NOSUCH',
--       '[{"id":1,"name":"x","name_seq":1,"name_area":"a","name_is_auto":true}]'::jsonb);
--   ROLLBACK;
